modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GPL3"


[[mods]]
modId = "justhammers"
version = "${version}"
displayName = "Just Hammers"
authors = "ErrorMikey"
description = '''
Add hammers to the game that are able to mine in a 3x3, 3x3x3, 5x5x3 and finally a 5x5x5! They're pretty awesome.
'''
#logoFile = ""

[[dependencies.justhammers]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.justhammers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.justhammers]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.17,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "justhammers.mixins.json"

[[mixins]]
config = "justhammers-common.mixins.json"
